doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

        second_level_cache:
            enabled: true
            log_enabled: true
            region_lock_lifetime: 600
            region_lifetime: 3600
            regions:
                entity_cache_region:
                    type: service
                    service: App\Doctrine\FileConcurrentRegion
                    lifetime: 6000
